### ISSUE TITLE
Error when no island is selected.

### ISSUE THREAD

**Issue by muhuk** [muhuk/grid-uv-packer#3]
```
Python: Traceback (most recent call last):
  File "/home/muhuk/.config/blender/3.4/scripts/addons/guvp/__init__.py", line 176, in execute
    self._calculate_udim_offset(
  File "/home/muhuk/.config/blender/3.4/scripts/addons/guvp/__init__.py", line 319, in _calculate_udim_offset
    self.udim_offset = self._calculate_udim_offset_closest(center)
  File "/home/muhuk/.config/blender/3.4/scripts/addons/guvp/__init__.py", line 382, in _calculate_udim_offset_closest
    tile_x: int = math.floor(center.x)
ValueError: cannot convert float NaN to integer
```

**Comment by muhuk** [comment]
Thanks @unfa.

**Comment by muhuk** [comment]
Blender 3.6.0 has this functionality built-in. Archiving this repository.
